terminate called after throwing an instance of 'ngpu_exception'
  what():  CUDA error
terminate called after throwing an instance of 'ngpu_exception'
  what():  CUDA error
[c1:26559] *** Process received signal ***
[c1:26559] Signal: Aborted (6)
[c1:26559] Signal code:  (-6)
[c1:26559] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7fda6e151520]
[c1:26559] [ 1] /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c)[0x7fda6e1a5a7c]
[c1:26559] [ 2] /lib/x86_64-linux-gnu/libc.so.6(raise+0x16)[0x7fda6e151476]
[c1:26559] [ 3] /lib/x86_64-linux-gnu/libc.so.6(abort+0xd3)[0x7fda6e1377f3]
[c1:26559] [ 4] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xa2bfe)[0x7fda5310fbfe]
[c1:26559] [ 5] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae28c)[0x7fda5311b28c]
[c1:26559] [ 6] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae2f7)[0x7fda5311b2f7]
[c1:26559] [ 7] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae558)[0x7fda5311b558]
[c1:26559] [ 8] /opt/nestgpu/lib/libnestgpu.so(+0x39599)[0x7fda4bf0f599]
[c1:26559] [ 9] /opt/nestgpu/lib/libnestgpu.so(checkNESTGPUInstance+0x2c)[0x7fda4bf7fb5c]
[c1:26559] [10] /opt/nestgpu/lib/libnestgpu.so(NESTGPU_SetOnException+0xc)[0x7fda4bf7fbcc]
[c1:26559] [11] /lib/x86_64-linux-gnu/libffi.so.8(+0x7e2e)[0x7fda6aed8e2e]
[c1:26559] [12] /lib/x86_64-linux-gnu/libffi.so.8(+0x4493)[0x7fda6aed5493]
[c1:26559] [13] /opt/pyenv/versions/3.10.7/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0x12e05)[0x7fda6aef0e05]
[c1:26559] [14] /opt/pyenv/versions/3.10.7/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0xc8d0)[0x7fda6aeea8d0]
[c1:26559] [15] /opt/pyenv/versions/3.10.7/bin/python(_PyObject_MakeTpCall+0x8c)[0x555c38d6c81c]
[c1:26559] [16] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x7bb1)[0x555c38d5c461]
[c1:26559] [17] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x555c38e16bb4]
[c1:26559] [18] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x67ce)[0x555c38d5b07e]
[c1:26559] [19] /opt/pyenv/versions/3.10.7/bin/python(PyEval_EvalCode+0xd0)[0x555c38e169e0]
[c1:26559] [20] /opt/pyenv/versions/3.10.7/bin/python(+0x2474cd)[0x555c38f404cd]
[c1:26559] [21] /opt/pyenv/versions/3.10.7/bin/python(+0x21ae23)[0x555c38f13e23]
[c1:26559] [22] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x176e)[0x555c38d5601e]
[c1:26559] [23] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x555c38e16bb4]
[c1:26559] [24] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x94dd)[0x555c38d5dd8d]
[c1:26559] [25] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x555c38e16bb4]
[c1:26559] [26] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x61b1)[0x555c38d5aa61]
[c1:26559] [27] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x555c38e16bb4]
[c1:26559] [28] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x67ce)[0x555c38d5b07e]
[c1:26559] [29] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x555c38e16bb4]
[c1:26559] *** End of error message ***
[c1:26561] *** Process received signal ***
[c1:26561] Signal: Aborted (6)
[c1:26561] Signal code:  (-6)
[c1:26561] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7f15f5125520]
[c1:26561] [ 1] /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c)[0x7f15f5179a7c]
[c1:26561] [ 2] /lib/x86_64-linux-gnu/libc.so.6(raise+0x16)[0x7f15f5125476]
[c1:26561] [ 3] /lib/x86_64-linux-gnu/libc.so.6(abort+0xd3)[0x7f15f510b7f3]
[c1:26561] [ 4] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xa2bfe)[0x7f15da0eebfe]
[c1:26561] [ 5] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae28c)[0x7f15da0fa28c]
[c1:26561] [ 6] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae2f7)[0x7f15da0fa2f7]
[c1:26561] [ 7] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae558)[0x7f15da0fa558]
[c1:26561] [ 8] /opt/nestgpu/lib/libnestgpu.so(+0x39599)[0x7f15d2ed8599]
[c1:26561] [ 9] /opt/nestgpu/lib/libnestgpu.so(checkNESTGPUInstance+0x2c)[0x7f15d2f48b5c]
[c1:26561] [10] /opt/nestgpu/lib/libnestgpu.so(NESTGPU_SetOnException+0xc)[0x7f15d2f48bcc]
[c1:26561] [11] /lib/x86_64-linux-gnu/libffi.so.8(+0x7e2e)[0x7f15f1eafe2e]
[c1:26561] [12] /lib/x86_64-linux-gnu/libffi.so.8(+0x4493)[0x7f15f1eac493]
[c1:26561] [13] /opt/pyenv/versions/3.10.7/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0x12e05)[0x7f15f1ec7e05]
[c1:26561] [14] /opt/pyenv/versions/3.10.7/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0xc8d0)[0x7f15f1ec18d0]
[c1:26561] [15] /opt/pyenv/versions/3.10.7/bin/python(_PyObject_MakeTpCall+0x8c)[0x5577d125b81c]
[c1:26561] [16] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x7bb1)[0x5577d124b461]
[c1:26561] [17] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x5577d1305bb4]
[c1:26561] [18] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x67ce)[0x5577d124a07e]
[c1:26561] [19] /opt/pyenv/versions/3.10.7/bin/python(PyEval_EvalCode+0xd0)[0x5577d13059e0]
[c1:26561] [20] /opt/pyenv/versions/3.10.7/bin/python(+0x2474cd)[0x5577d142f4cd]
[c1:26561] [21] /opt/pyenv/versions/3.10.7/bin/python(+0x21ae23)[0x5577d1402e23]
[c1:26561] [22] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x176e)[0x5577d124501e]
[c1:26561] [23] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x5577d1305bb4]
[c1:26561] [24] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x94dd)[0x5577d124cd8d]
[c1:26561] [25] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x5577d1305bb4]
[c1:26561] [26] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x61b1)[0x5577d1249a61]
[c1:26561] [27] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x5577d1305bb4]
[c1:26561] [28] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x67ce)[0x5577d124a07e]
[c1:26561] [29] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x5577d1305bb4]
[c1:26561] *** End of error message ***
SIGABRT: abort
PC=0x47cdab m=0 sigcode=0

goroutine 1 [running, locked to thread]:
syscall.RawSyscall(0x3e, 0x6766, 0x6, 0x0, 0x0, 0xc000024060, 0xc000024060)
	/usr/lib/golang/src/syscall/asm_linux_amd64.s:78 +0x2b fp=0xc000197e70 sp=0xc000197e68 pc=0x47cdab
syscall.Kill(0x6766, 0x6, 0x0, 0x0)
	/usr/lib/golang/src/syscall/zsyscall_linux_amd64.go:597 +0x4b fp=0xc000197eb8 sp=0xc000197e70 pc=0x479bcb
github.com/sylabs/singularity/internal/app/starter.Master.func2()
	internal/app/starter/master_linux.go:152 +0x61 fp=0xc000197f00 sp=0xc000197eb8 pc=0x7928f1
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute.func1()
	internal/pkg/util/mainthread/mainthread.go:21 +0x2f fp=0xc000197f28 sp=0xc000197f00 pc=0x790f4f
main.main()
	cmd/starter/main_linux.go:102 +0x5f fp=0xc000197f60 sp=0xc000197f28 pc=0x972bbf
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:203 +0x21e fp=0xc000197fe0 sp=0xc000197f60 pc=0x433b4e
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000197fe8 sp=0xc000197fe0 pc=0x45f7c1

goroutine 19 [syscall]:
os/signal.signal_recv(0xb9da80)
	/usr/lib/golang/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/lib/golang/src/os/signal/signal_unix.go:29 +0x41

goroutine 5 [chan receive]:
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute(0xc0002cfbd0)
	internal/pkg/util/mainthread/mainthread.go:24 +0xb4
github.com/sylabs/singularity/internal/app/starter.Master(0x7, 0x5, 0x67c1, 0xc00000e900)
	internal/app/starter/master_linux.go:151 +0x44c
main.startup()
	cmd/starter/main_linux.go:75 +0x53e
created by main.main
	cmd/starter/main_linux.go:98 +0x35

rax    0x0
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x6766
rsi    0x6
rbp    0xc000197ea8
rsp    0xc000197e68
r8     0x0
r9     0x0
r10    0x0
r11    0x202
r12    0xf3
r13    0x0
r14    0xb83e88
r15    0x0
rip    0x47cdab
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
SIGABRT: abort
PC=0x47cdab m=0 sigcode=0

goroutine 1 [running, locked to thread]:
syscall.RawSyscall(0x3e, 0x6764, 0x6, 0x0, 0x0, 0xc000024060, 0xc000024060)
	/usr/lib/golang/src/syscall/asm_linux_amd64.s:78 +0x2b fp=0xc0001bbe70 sp=0xc0001bbe68 pc=0x47cdab
syscall.Kill(0x6764, 0x6, 0x0, 0x0)
	/usr/lib/golang/src/syscall/zsyscall_linux_amd64.go:597 +0x4b fp=0xc0001bbeb8 sp=0xc0001bbe70 pc=0x479bcb
github.com/sylabs/singularity/internal/app/starter.Master.func2()
	internal/app/starter/master_linux.go:152 +0x61 fp=0xc0001bbf00 sp=0xc0001bbeb8 pc=0x7928f1
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute.func1()
	internal/pkg/util/mainthread/mainthread.go:21 +0x2f fp=0xc0001bbf28 sp=0xc0001bbf00 pc=0x790f4f
main.main()
	cmd/starter/main_linux.go:102 +0x5f fp=0xc0001bbf60 sp=0xc0001bbf28 pc=0x972bbf
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:203 +0x21e fp=0xc0001bbfe0 sp=0xc0001bbf60 pc=0x433b4e
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0001bbfe8 sp=0xc0001bbfe0 pc=0x45f7c1

goroutine 19 [syscall]:
os/signal.signal_recv(0xb9da80)
	/usr/lib/golang/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/lib/golang/src/os/signal/signal_unix.go:29 +0x41

goroutine 5 [chan receive]:
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute(0xc0002dbbd0)
	internal/pkg/util/mainthread/mainthread.go:24 +0xb4
github.com/sylabs/singularity/internal/app/starter.Master(0x7, 0x5, 0x67bf, 0xc00000e800)
	internal/app/starter/master_linux.go:151 +0x44c
main.startup()
	cmd/starter/main_linux.go:75 +0x53e
created by main.main
	cmd/starter/main_linux.go:98 +0x35

rax    0x0
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x6764
rsi    0x6
rbp    0xc0001bbea8
rsp    0xc0001bbe68
r8     0x0
r9     0x0
r10    0x0
r11    0x202
r12    0xf3
r13    0x0
r14    0xb83e88
r15    0x0
rip    0x47cdab
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[23449,1],3]
  Exit code:    2
--------------------------------------------------------------------------
