terminate called after throwing an instance of 'ngpu_exception'
  what():  CUDA error
[c1:14328] *** Process received signal ***
[c1:14328] Signal: Aborted (6)
[c1:14328] Signal code:  (-6)
[c1:14328] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7fc07870d520]
[c1:14328] [ 1] /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c)[0x7fc078761a7c]
[c1:14328] [ 2] /lib/x86_64-linux-gnu/libc.so.6(raise+0x16)[0x7fc07870d476]
[c1:14328] [ 3] /lib/x86_64-linux-gnu/libc.so.6(abort+0xd3)[0x7fc0786f37f3]
[c1:14328] [ 4] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xa2bfe)[0x7fc05d704bfe]
[c1:14328] [ 5] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae28c)[0x7fc05d71028c]
[c1:14328] [ 6] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae2f7)[0x7fc05d7102f7]
[c1:14328] [ 7] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae558)[0x7fc05d710558]
[c1:14328] [ 8] /opt/nestgpu/lib/libnestgpu.so(+0x3a1db)[0x7fc0563a11db]
[c1:14328] [ 9] /opt/nestgpu/lib/libnestgpu.so(checkNESTGPUInstance+0x2c)[0x7fc05641361c]
[c1:14328] [10] /opt/nestgpu/lib/libnestgpu.so(NESTGPU_SetOnException+0xc)[0x7fc05641368c]
[c1:14328] [11] /lib/x86_64-linux-gnu/libffi.so.8(+0x7e2e)[0x7fc077c8ce2e]
[c1:14328] [12] /lib/x86_64-linux-gnu/libffi.so.8(+0x4493)[0x7fc077c89493]
[c1:14328] [13] /opt/pyenv/versions/3.10.7/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0x12e05)[0x7fc077ca4e05]
[c1:14328] [14] /opt/pyenv/versions/3.10.7/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0xc8d0)[0x7fc077c9e8d0]
[c1:14328] [15] /opt/pyenv/versions/3.10.7/bin/python(_PyObject_MakeTpCall+0x8c)[0x555b3c41081c]
[c1:14328] [16] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x7bb1)[0x555b3c400461]
[c1:14328] [17] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x555b3c4babb4]
[c1:14328] [18] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x67ce)[0x555b3c3ff07e]
[c1:14328] [19] /opt/pyenv/versions/3.10.7/bin/python(PyEval_EvalCode+0xd0)[0x555b3c4ba9e0]
[c1:14328] [20] /opt/pyenv/versions/3.10.7/bin/python(+0x2474cd)[0x555b3c5e44cd]
[c1:14328] [21] /opt/pyenv/versions/3.10.7/bin/python(+0x21ae23)[0x555b3c5b7e23]
[c1:14328] [22] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x176e)[0x555b3c3fa01e]
[c1:14328] [23] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x555b3c4babb4]
[c1:14328] [24] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x94dd)[0x555b3c401d8d]
[c1:14328] [25] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x555b3c4babb4]
[c1:14328] [26] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x61b1)[0x555b3c3fea61]
[c1:14328] [27] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x555b3c4babb4]
[c1:14328] [28] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x67ce)[0x555b3c3ff07e]
[c1:14328] [29] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x555b3c4babb4]
[c1:14328] *** End of error message ***
terminate called after throwing an instance of 'ngpu_exception'
  what():  CUDA error
[c1:14327] *** Process received signal ***
[c1:14327] Signal: Aborted (6)
[c1:14327] Signal code:  (-6)
[c1:14327] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7f3517229520]
[c1:14327] [ 1] /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c)[0x7f351727da7c]
[c1:14327] [ 2] /lib/x86_64-linux-gnu/libc.so.6(raise+0x16)[0x7f3517229476]
[c1:14327] [ 3] /lib/x86_64-linux-gnu/libc.so.6(abort+0xd3)[0x7f351720f7f3]
[c1:14327] [ 4] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xa2bfe)[0x7f34fc033bfe]
[c1:14327] [ 5] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae28c)[0x7f34fc03f28c]
[c1:14327] [ 6] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae2f7)[0x7f34fc03f2f7]
[c1:14327] [ 7] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae558)[0x7f34fc03f558]
[c1:14327] [ 8] /opt/nestgpu/lib/libnestgpu.so(+0x3a1db)[0x7f34f4eac1db]
[c1:14327] [ 9] /opt/nestgpu/lib/libnestgpu.so(checkNESTGPUInstance+0x2c)[0x7f34f4f1e61c]
[c1:14327] [10] /opt/nestgpu/lib/libnestgpu.so(NESTGPU_SetOnException+0xc)[0x7f34f4f1e68c]
[c1:14327] [11] /lib/x86_64-linux-gnu/libffi.so.8(+0x7e2e)[0x7f35140afe2e]
[c1:14327] [12] /lib/x86_64-linux-gnu/libffi.so.8(+0x4493)[0x7f35140ac493]
[c1:14327] [13] /opt/pyenv/versions/3.10.7/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0x12e05)[0x7f35140c7e05]
[c1:14327] [14] /opt/pyenv/versions/3.10.7/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0xc8d0)[0x7f35140c18d0]
[c1:14327] [15] /opt/pyenv/versions/3.10.7/bin/python(_PyObject_MakeTpCall+0x8c)[0x55a714cc681c]
[c1:14327] [16] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x7bb1)[0x55a714cb6461]
[c1:14327] [17] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x55a714d70bb4]
[c1:14327] [18] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x67ce)[0x55a714cb507e]
[c1:14327] [19] /opt/pyenv/versions/3.10.7/bin/python(PyEval_EvalCode+0xd0)[0x55a714d709e0]
[c1:14327] [20] /opt/pyenv/versions/3.10.7/bin/python(+0x2474cd)[0x55a714e9a4cd]
[c1:14327] [21] /opt/pyenv/versions/3.10.7/bin/python(+0x21ae23)[0x55a714e6de23]
[c1:14327] [22] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x176e)[0x55a714cb001e]
[c1:14327] [23] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x55a714d70bb4]
[c1:14327] [24] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x94dd)[0x55a714cb7d8d]
[c1:14327] [25] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x55a714d70bb4]
[c1:14327] [26] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x61b1)[0x55a714cb4a61]
[c1:14327] [27] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x55a714d70bb4]
[c1:14327] [28] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x67ce)[0x55a714cb507e]
[c1:14327] [29] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x55a714d70bb4]
[c1:14327] *** End of error message ***
SIGABRT: abort
PC=0x47cdab m=0 sigcode=0

goroutine 1 [running, locked to thread]:
syscall.RawSyscall(0x3e, 0x37a4, 0x6, 0x0, 0x0, 0xc000024360, 0xc000024360)
	/usr/lib/golang/src/syscall/asm_linux_amd64.s:78 +0x2b fp=0xc0001a7e70 sp=0xc0001a7e68 pc=0x47cdab
syscall.Kill(0x37a4, 0x6, 0x0, 0x0)
	/usr/lib/golang/src/syscall/zsyscall_linux_amd64.go:597 +0x4b fp=0xc0001a7eb8 sp=0xc0001a7e70 pc=0x479bcb
github.com/sylabs/singularity/internal/app/starter.Master.func2()
	internal/app/starter/master_linux.go:152 +0x61 fp=0xc0001a7f00 sp=0xc0001a7eb8 pc=0x7928f1
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute.func1()
	internal/pkg/util/mainthread/mainthread.go:21 +0x2f fp=0xc0001a7f28 sp=0xc0001a7f00 pc=0x790f4f
main.main()
	cmd/starter/main_linux.go:102 +0x5f fp=0xc0001a7f60 sp=0xc0001a7f28 pc=0x972bbf
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:203 +0x21e fp=0xc0001a7fe0 sp=0xc0001a7f60 pc=0x433b4e
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0001a7fe8 sp=0xc0001a7fe0 pc=0x45f7c1

goroutine 6 [syscall]:
os/signal.signal_recv(0xb9da80)
	/usr/lib/golang/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/lib/golang/src/os/signal/signal_unix.go:29 +0x41

goroutine 8 [chan receive]:
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute(0xc0002cfbb0)
	internal/pkg/util/mainthread/mainthread.go:24 +0xb4
github.com/sylabs/singularity/internal/app/starter.Master(0x7, 0x5, 0x37f7, 0xc00000eac0)
	internal/app/starter/master_linux.go:151 +0x44c
main.startup()
	cmd/starter/main_linux.go:75 +0x53e
created by main.main
	cmd/starter/main_linux.go:98 +0x35

rax    0x0
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x37a4
rsi    0x6
rbp    0xc0001a7ea8
rsp    0xc0001a7e68
r8     0x0
r9     0x0
r10    0x0
r11    0x202
r12    0xff
r13    0x0
r14    0xb83b64
r15    0x0
rip    0x47cdab
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
SIGABRT: abort
PC=0x47cdab m=0 sigcode=0

goroutine 1 [running, locked to thread]:
syscall.RawSyscall(0x3e, 0x37a2, 0x6, 0x0, 0x0, 0xc000024060, 0xc000024060)
	/usr/lib/golang/src/syscall/asm_linux_amd64.s:78 +0x2b fp=0xc000191e70 sp=0xc000191e68 pc=0x47cdab
syscall.Kill(0x37a2, 0x6, 0x0, 0x0)
	/usr/lib/golang/src/syscall/zsyscall_linux_amd64.go:597 +0x4b fp=0xc000191eb8 sp=0xc000191e70 pc=0x479bcb
github.com/sylabs/singularity/internal/app/starter.Master.func2()
	internal/app/starter/master_linux.go:152 +0x61 fp=0xc000191f00 sp=0xc000191eb8 pc=0x7928f1
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute.func1()
	internal/pkg/util/mainthread/mainthread.go:21 +0x2f fp=0xc000191f28 sp=0xc000191f00 pc=0x790f4f
main.main()
	cmd/starter/main_linux.go:102 +0x5f fp=0xc000191f60 sp=0xc000191f28 pc=0x972bbf
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:203 +0x21e fp=0xc000191fe0 sp=0xc000191f60 pc=0x433b4e
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000191fe8 sp=0xc000191fe0 pc=0x45f7c1

goroutine 6 [syscall]:
os/signal.signal_recv(0xb9da80)
	/usr/lib/golang/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/lib/golang/src/os/signal/signal_unix.go:29 +0x41

goroutine 8 [chan receive]:
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute(0xc0002bbb90)
	internal/pkg/util/mainthread/mainthread.go:24 +0xb4
github.com/sylabs/singularity/internal/app/starter.Master(0x7, 0x5, 0x37f8, 0xc00000f1a0)
	internal/app/starter/master_linux.go:151 +0x44c
main.startup()
	cmd/starter/main_linux.go:75 +0x53e
created by main.main
	cmd/starter/main_linux.go:98 +0x35

rax    0x0
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x37a2
rsi    0x6
rbp    0xc000191ea8
rsp    0xc000191e68
r8     0x0
r9     0x0
r10    0x0
r11    0x202
r12    0xf3
r13    0x0
r14    0xb83e88
r15    0x0
rip    0x47cdab
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[2907,1],3]
  Exit code:    2
--------------------------------------------------------------------------
